"""empty message

Revision ID: 4facb31980bb
Revises: 772b30238546
Create Date: 2023-09-16 12:21:34.079905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4facb31980bb'
down_revision = '772b30238546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_of_entry', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('days_for_expiry', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('days_for_expiry')
        batch_op.drop_column('time_of_entry')

    # ### end Alembic commands ###
